import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import codexImageGen, {
	buildRequestBody,
	CODEX_RESPONSES_URL,
	DEFAULT_MODEL,
	extractChatGptAccountId,
	mimeForFormat,
	parseCodexSseText,
	resolveSaveConfig,
	saveImage,
} from "../extensions/codex-image-gen/index.ts";

const JWT_CLAIM_PATH = "https://api.openai.com/auth";

function fakeCodexToken(accountId = "acct_test") {
	const header = Buffer.from(JSON.stringify({ alg: "none" })).toString(
		"base64url",
	);
	const payload = Buffer.from(
		JSON.stringify({ [JWT_CLAIM_PATH]: { chatgpt_account_id: accountId } }),
	).toString("base64url");
	return `${header}.${payload}.signature`;
}

function imageSse(base64 = Buffer.from("fake-image-bytes").toString("base64")) {
	return [
		`data: ${JSON.stringify({ type: "response.created", response: { id: "resp_test" } })}`,
		"",
		`data: ${JSON.stringify({
			type: "response.output_item.done",
			item: {
				type: "image_generation_call",
				id: "ig_test",
				status: "completed",
				result: base64,
				revised_prompt: "A centered blue circle on white.",
			},
		})}`,
		"",
		`data: ${JSON.stringify({ type: "response.completed", response: { id: "resp_test", usage: { input_tokens: 1 } } })}`,
		"",
	].join("\n");
}

test("extractChatGptAccountId reads Pi openai-codex JWT claims", () => {
	assert.equal(extractChatGptAccountId(fakeCodexToken("acct_123")), "acct_123");
	assert.throws(() => extractChatGptAccountId("not-a-jwt"), /not a JWT/);
});

test("buildRequestBody enables Codex image_generation with output controls", () => {
	const body = buildRequestBody(
		{
			prompt: "draw a blue circle",
			quality: "low",
			size: "1024x1024",
			action: "generate",
		},
		DEFAULT_MODEL,
		"png",
		"session-1",
	);

	assert.equal(body.model, DEFAULT_MODEL);
	assert.equal(body.stream, true);
	assert.equal(body.prompt_cache_key, "session-1");
	assert.deepEqual(body.tools, [
		{
			type: "image_generation",
			output_format: "png",
			quality: "low",
			size: "1024x1024",
			action: "generate",
		},
	]);
	assert.deepEqual(body.input[0].content[0], {
		type: "input_text",
		text: "draw a blue circle",
	});
});

test("parseCodexSseText extracts image generation call and usage", () => {
	const parsed = parseCodexSseText(imageSse("aW1hZ2U="));
	assert.equal(parsed.responseId, "resp_test");
	assert.equal(parsed.image?.id, "ig_test");
	assert.equal(parsed.image?.result, "aW1hZ2U=");
	assert.equal(parsed.image?.revisedPrompt, "A centered blue circle on white.");
	assert.deepEqual(parsed.usage, { input_tokens: 1 });
});

test("resolveSaveConfig and saveImage persist generated bytes", async () => {
	const cwd = mkdtempSync(path.join(tmpdir(), "pi-codex-image-gen-save-"));
	const saveConfig = resolveSaveConfig(
		{ prompt: "x", save: "project" },
		cwd,
		"session/id",
		{},
	);
	assert.equal(saveConfig.mode, "project");
	assert.equal(
		saveConfig.outputDir,
		path.join(cwd, ".pi", "generated-images", "session_id"),
	);

	const saved = await saveImage(
		Buffer.from("hello").toString("base64"),
		"jpeg",
		saveConfig.outputDir!,
		"call/1",
	);
	assert.equal(path.basename(saved), "call_1.jpg");
	assert.equal(readFileSync(saved, "utf8"), "hello");
	assert.equal(mimeForFormat("jpeg"), "image/jpeg");
});

test("codex_generate_image tool uses openai-codex auth and saves mocked response", async (t) => {
	const originalFetch = globalThis.fetch;
	const cwd = mkdtempSync(path.join(tmpdir(), "pi-codex-image-gen-tool-"));
	const calls: Array<{ url: string; init: RequestInit }> = [];
	globalThis.fetch = (async (url: string, init: RequestInit) => {
		calls.push({ url, init });
		return new Response(imageSse(), {
			status: 200,
			headers: { "content-type": "text/event-stream" },
		});
	}) as typeof fetch;
	t.after(() => {
		globalThis.fetch = originalFetch;
	});

	let tool: any;
	codexImageGen({
		registerTool(definition: unknown) {
			tool = definition;
		},
	} as any);
	assert.equal(tool.name, "codex_generate_image");

	const updates: unknown[] = [];
	const result = await tool.execute(
		"tool-call-id",
		{ prompt: "draw a blue circle", save: "project", outputFormat: "png" },
		undefined,
		(update: unknown) => updates.push(update),
		{
			cwd,
			modelRegistry: {
				find: () => ({ id: DEFAULT_MODEL }),
				getApiKeyForProvider: async () => fakeCodexToken("acct_tool"),
			},
			sessionManager: { getSessionId: () => "session-tool" },
		},
	);

	assert.equal(calls.length, 1);
	assert.equal(calls[0].url, CODEX_RESPONSES_URL);
	const headers = calls[0].init.headers as Record<string, string>;
	assert.equal(headers["chatgpt-account-id"], "acct_tool");
	assert.match(headers.Authorization, /^Bearer /);
	assert.ok(
		!headers.Authorization.includes("acct_tool"),
		"JWT should not be derived from account id string",
	);

	assert.equal(result.details.provider, "openai-codex");
	assert.equal(result.details.backendImageModel, "gpt-image-2");
	assert.equal(result.details.saveMode, "project");
	assert.ok(
		existsSync(result.details.savedPath),
		`missing saved image ${result.details.savedPath}`,
	);
	assert.equal(
		readFileSync(result.details.savedPath, "utf8"),
		"fake-image-bytes",
	);
	assert.equal(result.content[1].type, "image");
	assert.equal(result.content[1].mimeType, "image/png");
	assert.ok(updates.length >= 2);
});

test("codex_generate_image reports missing openai-codex credentials", async () => {
	let tool: any;
	codexImageGen({
		registerTool(definition: unknown) {
			tool = definition;
		},
	} as any);
	await assert.rejects(
		() =>
			tool.execute("tool-call-id", { prompt: "draw" }, undefined, undefined, {
				cwd: process.cwd(),
				modelRegistry: {
					find: () => undefined,
					getApiKeyForProvider: async () => undefined,
				},
				sessionManager: { getSessionId: () => "session" },
			}),
		/Missing openai-codex credentials/,
	);
});
